---
# Ansible playbook to set my typical Linux system
- name : hello, Ansible!
  hosts: localhost
  tasks:
          - name: saying hi
            command: 'echo {{ greeting | default("hi!") }}'
            
            ### so redirection of any kind did not work! ###
            #- name: logging wd to ~
            #command: >
                    #echo "[$(date +'%F %T')] : $(pwd)" | tee -a $HOME/pwd.log
            #- name: logging wd to ~ using input redirection
                    #command: >
                    #cat >> $HOME/pwd.log <<<(echo "[$(date +'%F %T')] : $(pwd)") 
            #- name: logging wd to ~ using heredoc
            #command: >
                    #cat << EOM >> $HOME/pwd.log
                    #[$(date +'%F %T')] : $(pwd)
                    #EOM
            ### so redirection of any kind did not work! ###

            # i don't want to be disappointed that NOTHING i tried worked!
          - name: use the example
            command: >
                    touch ~/ansible_was_here
                    warn=false
          - name: use shell module for redirection!
            shell: >
                    echo "[$(date +'%F %T')] : $(pwd)" | tee -a $HOME/pwd.log
                    # yeee. it worked!
          - name: use different variables
            command: echo {{ variables.stringVersion | default(variables.version.major) }}
